name: Docker Image CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
       registry: ghcr.io
       username: ${{github.actor}}
       password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/int2001/wldataservice:latest
    - name: Push the tagged Docker image
      run: docker push ghcr.io/int2001/wldataservice:latest
